FLOGRAM/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from accounts.sitemaps import StaticViewsSitemap
from django.contrib.sitemaps.views import sitemap

app_name = 'FLOGRAM'

sitemaps = {
    'static' : StaticViewsSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name="aboutUs"),
    path('Media-Literacy', views.Media, name="Media-Literacy"),
    path('', views.home, name="homePage"),
    path('accounts/', include('accounts.urls'), name="accounts"),
    path('sitemap.xml', sitemap, {'sitemaps' : sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]
urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name="loginpage"),
    path('signup/', views.signup, name="signup"),
    path('verify/<str:code>', views.verify_code, name="verify"),
    path('sponsors/', views.sponsors, name="sponsors"),
    path('<str:username>', views.influencers, name="influencers")
]

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <title>About Us</title>
    <style>
        @import "https://fonts.googleapis.com/css?family=Josefin+Sans:400,700";
        .split {
        height: 100%;
        width: 50%;
        position: fixed;
        top: 0;
        overflow-x: hidden;
        }


        .left {
        left: 0;
        background-color: #dedfe3;
        }

        .right {
        right: 0;
        background-color: rgb(219 219 217);
        }

        body {
            margin: 0;
            padding: 0;
            font-family: "Josefin Sans", sans-serif;
            background-color: #eee;
        }
        body a {
            color: #ffffff;
            text-decoration: none;
        }
        
        .card {
            position: relative;
            top: 50%;
            left: 50%;
            height: 500px;
            width: 350px;
            transform: translate(-50%, -50%);
            transform-style: preserve-3d;
            perspective: 600px;
            transition: 0.5s;
        }
        .card:hover .f-card-front {
            transform: rotateX(-180deg);
        }
        .card:hover .s-card-front {
            transform: rotateX(-180deg);
        }
        .card:hover .card-back {
            transform: rotateX(0deg);
        }
        
        .f-card-front {
            height: 100%;
            width: 100%;
            background-image: url(https://lms.rouzbeh.info/pluginfile.php/2274/user/icon/moove/f1?rev=11378449);
            background-position: 50% 50%;
            background-size: cover;
            position: absolute;
            top: 0;
            left: 0;
            background-color: #000000;
            backface-visibility: hidden;
            transform: rotateX(0deg);
            transition: 0.5s;
            background-repeat: no-repeat;

        }
        .s-card-front {
            height: 100%;
            width: 100%;
            background-image: url(https://lms.rouzbeh.info/pluginfile.php/2233/user/icon/moove/f1?rev=);
            background-position: 50% 50%;
            background-size: cover;
            position: absolute;
            top: 0;
            left: 0;
            background-color: #000000;
            backface-visibility: hidden;
            transform: rotateX(0deg);
            transition: 0.5s;
            background-repeat: no-repeat;

        }
        
        .card-back {
            height: 100%;
            width: 100%;
            position: absolute;
            top: 0;
            left: 0;
            background-color: #000000;
            backface-visibility: hidden;
            transform: rotateX(180deg);
            transition: 0.5s;
            color: #ffffff;
            text-align: center;
        }
        .card-back h2 {
            margin: 60% auto 35% auto;
            font-size: 26px;
        }
        .card-back h2 span {
            font-size: 20px;
        }
        .card-back a {
            height: 20px;
            width: 20px;
            padding: 5px 5px;
            border-radius: 4px;
            line-height: 20px;
        }
        .card-back a:hover {
            color: #000000;
            background-color: #fff;}
        

    </style>
</head>
<body>
    <div class="split left">
        <div class="card">
            <div class="s-card-front"></div>
            <div class="card-back">
                <h2>Amirhossein Radmehr<br><span>Developer</span><br><span>Student</span><br><span>Studying at Rouzbeh</span></h2>
                <div class="social-icons">
                    <a href="https://t.me/Radmehr38" class="fa fa-telegram" aria-hidden="true"></a>
                    <a href="https://github.com/amirHosseinRadmehr" class="fa fa-github" aria-hidden="true"></a>
                    <a href="https://www.instagram.com/amirhradmehr123/" class="fa fa-instagram" aria-hidden="true"></a>
                </div>
            </div>
    </div> 
    </div>
    
    <div class="split right">
        <div class="card">
            <div class="f-card-front"></div>
            <div class="card-back">
                <h2>Amirhossein Moqimi<br><span>Developer</span><br><span>Student</span><br><span>Studying at Rouzbeh</span></h2>
                <div class="social-icons">
                    <a href="https://t.me/Amir_khan_00" class="fa fa-telegram" aria-hidden="true"></a>
                    <a href="https://github.com/amir-hossein-moqimi" class="fa fa-github" aria-hidden="true"></a>
                    <a href="https://www.instagram.com/amir_hossein_moqimi/" class="fa fa-instagram" aria-hidden="true"></a>
                </div>
            </div>
    </div> 
    </div>
    
</body>
</html>

templates/influencer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if can_edit %}
    <link rel="stylesheet" href="../static/inf.css">
    {% else %}
    <link rel="stylesheet" href="../static/inf_view.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    {% endif %}
    <title>{{influencer}}</title>
</head>
<body>
    {% if can_edit %}
    <div class="container">
        <img class="brand-logo" src="../static/profs/{{id}}.jpg"></img>
        <div class="brand-title">{{influencer}}</div>
        <div class="inputs">
        <form action="" method="post">
        {% csrf_token %}
          <label>description</label>
          <input name="description" type="text" placeholder="add description here" />
          <label>money needed</label>
          <input name="money" type="number" placeholder="add your needed money in dollors" />
          {% if result != None %}
          <p class="font-bold text-red-800 pt-5 ml-3">{{result}}</p>
          {% endif %}
          <button type="submit">submit</button>
        </form>
        </div>
    </div>
    {% else %}
    <div class="main-container">
        <div class="heading">
          <h1 class="heading__title">{{requested.profile.Instagram}}</h1>
          <img class="brand-logo" src="../static/profs/{{id}}.jpg"></img>
        <div class="cards">
          <div class="card card-1">
            <div class="card__icon"><i class="fa fa-comment"></i></div>
            <h2 class="card__title">Average comments : {{object.get_average_comments}}</h2>
          </div>
          <div class="card card-2">
            <div class="card__icon"><i class="fa fa-eye"></i></div>
      
            <h2 class="card__title">Average view : {{object.get_average_view}}</h2>
      
          </div>
          <div class="card card-3">
            <div class="card__icon"><i class="fa fa-thumbs-up"></i></div>
      
            <h2 class="card__title">Average likes : {{object.get_average_likes}}</h2>
      
          </div>
          <div class="card card-4">
            <div class="card__icon"><i class="fa fa-info"></i></div>
      
            <h2 class="card__title">description : {{requested.profile.description}}</h2>
      
          </div>
          <div class="card card-5">
            <div class="card__icon"><i class="fa fa-money"></i></div>
      
            <h2 class="card__title">money needed : {{requested.profile.money}}$</h2>
      
          </div>
      
        </div>
      </div>
    {% endif %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Log In</title>
    <link
      href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <script src="https://kit.fontawesome.com/703024bbc3.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <style>
    .i {
      color: #d9d9d9;
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .i i {
      transition: 0.3s;
    }

    .input-div > div {
      position: relative;
      height: 45px;
    }

    .input-div > div > h5 {
      position: absolute;
      left: 10px;
      top: 50%;
      transform: translateY(-50%);
      color: #999;
      font-size: 18px;
      transition: 0.3s;
    }

    .input-div:before,
    .input-div:after {
      content: "";
      position: absolute;
      bottom: -2px;
      width: 0%;
      height: 2px;
      background-color: #38d39f;
      transition: 0.4s;
    }

    .input-div:before {
      right: 50%;
    }

    .input-div:after {
      left: 50%;
    }

    .input-div.focus:before,
    .input-div.focus:after {
      width: 50%;
    }

    .input-div.focus > div > h5 {
      top: -5px;
      font-size: 15px;
    }

    .input-div.focus > .i > i {
      color: #38d39f;
    }
  </style>
  <body class="bg-gray-300" style="font-family: Roboto">
    <div class="h-screen flex justify-center items-center">
      <div class="bg-white rounded-lg w-4/5 max-w-2xl px-16 py-16">
        <form action="{% url 'accounts:loginpage' %}" method="post">
          {% csrf_token %}
          <div class="flex font-bold justify-center">
            <a href="{% url 'homePage' %}">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                version="1.1"
                id="Layer_1"
                x="0px"
                y="0px"
                viewBox="0 0 117 113"
                style="enable-background: new 0 0 117 113"
                xml:space="preserve"
                class="fill-current text-white h-12 w-12 mr-2"
              >
                <style type="text/css">
                  .st0 {
                    fill: #ff9900;
                  }
                </style>
                <g
                  transform="translate(0.000000,113.000000) scale(0.100000,-0.100000)"
                >
                  <path
                    class="st0"
                    d="M145,961v-50h203h203l1,50l1,50H349H145V961z M525,966c0-14-6-25-12-26c-76-3-331,1-338,6c-7,4-6,13,0,26   c10,18,23,19,180,19h170V966z"
                  />
                  <path
                    class="st0"
                    d="M903,761l3-250H770H633l4-47l3-48l183-3l182-2v300v300h-52h-53L903,761z M977,739c2-139,2-263,0-275   c-3-23-5-23-161-23H658l5,25c4,25,5,25,116,25c74,0,118,4,129,13c19,14,24,81,26,335c1,144,2,152,21,152S974,982,977,739z"
                  />
                  <path
                    class="st0"
                    d="M145,599V411h50h49l3,136l3,136l127-1l127-2l-1,50v50l-179,3l-179,3V599z M480,739c-2-22-6-23-93-24   c-50-1-96-5-102-9s-18-1-27,7c-9,7-14,8-10,2c3-6-2-20-12-30c-14-16-17-35-16-109c1-50,0-100-3-112c-6-31-38-30-44,1   c-4,19-3,195,1,279c1,15,15,17,154,17C481,761,482,761,480,739z"
                  />
                </g>
                <path
                  class="st0"
                  d="M7.7,84.6c0,1,10,1.2,50.5,1.1c28.5,0,50.7-0.5,51-1c0.4-0.5-20.7-1-50.5-1.1C17.7,83.4,7.7,83.6,7.7,84.6z"
                />
              </svg>
            </a>
          </div>
          <h2 class="text-3xl text-center text-gray-700 mb-4">Login Form</h2>
          <div
            class="input-div border-b-2 relative grid my-5 py-1 focus:outline-none"
            style="grid-template-columns: 7% 93%"
          >
            <div class="i">
              <i class="fas fa-user"></i>
            </div>
            <div class="div">
              <h5>Username</h5>
              <input
                type="text"
                class="absolute w-full h-full py-2 px-3 outline-none inset-0 text-gray-700"
                style="background: none"
                name="username"
              />
            </div>
          </div>
          <div
            class="input-div border-b-2 relative grid my-5 py-1 focus:outline-none"
            style="grid-template-columns: 7% 93%"
          >
            <div class="i">
              <i class="fas fa-lock"></i>
            </div>
            <div class="div">
              <h5>Password</h5>
              <input
                type="password"
                class="absolute w-full h-full py-2 px-3 outline-none inset-0 text-gray-700"
                style="background: none"
                name="password"
              />
            </div>
            {% if haserror %}
            <p class="font-bold text-red-800 pt-5 ml-3">invalid username or password!</p>
            {% endif %}
          </div>
          <button
            type="submit"
            class="w-full py-2 rounded-full bg-green-600 text-gray-100 focus:outline-none"
          >
            Login
          </button>
        </form>
      </div>
    </div>
    <script>
      const inputs = document.querySelectorAll("input");

      function addcl() {
        let parent = this.parentNode.parentNode;
        parent.classList.add("focus");
      }

      function remcl() {
        let parent = this.parentNode.parentNode;
        if (this.value == "") {
          parent.classList.remove("focus");
        }
      }

      inputs.forEach((input) => {
        input.addEventListener("focus", addcl);
        input.addEventListener("blur", remcl);
      });
    </script>
  </body>
</html>

templates/signup.html
<!DOCTYPE html>
<html>
  <head>
    <title>Sign Up</title>
    <link
      href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <script src="https://kit.fontawesome.com/703024bbc3.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <style>
    body {
      min-width: 300px;
    }
    .containerra {
      display: flex;
      flex-wrap: wrap;
    }
    .containerra label {
      flex: 1 1 50px;
      text-align: center;
    }
    .i {
      color: #d9d9d9;
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .i i {
      transition: 0.3s;
    }

    .input-div > div {
      position: relative;
      height: 45px;
    }

    .input-div > div > h5 {
      position: absolute;
      left: 10px;
      top: 50%;
      transform: translateY(-50%);
      color: #999;
      font-size: 18px;
      transition: 0.3s;
    }

    .input-div:before,
    .input-div:after {
      content: "";
      position: absolute;
      bottom: -2px;
      width: 0%;
      height: 2px;
      background-color: #38d39f;
      transition: 0.4s;
    }

    .input-div:before {
      right: 50%;
    }

    .input-div:after {
      left: 50%;
    }

    .input-div.focus:before,
    .input-div.focus:after {
      width: 50%;
    }

    .input-div.focus > div > h5 {
      top: -5px;
      font-size: 15px;
    }

    .input-div.focus > .i > i {
      color: #38d39f;
    }
    /* .wrapper{
  display: inline-flex;
  background: #fff;
  height: 100px;
  width: 400px;
  align-items: center;
  justify-content: space-evenly;
  border-radius: 5px;
  padding: 20px 15px;
  box-shadow: 5px 5px 30px rgba(0,0,0,0.2);
} */
    .option {
      background: #fff;
      height: 100%;
      width: 100%;
      display: flex;
      align-items: center;
      justify-content: space-evenly;
      margin: 0 10px;
      border-radius: 5px;
      cursor: pointer;
      padding: 0 10px;
      border: 2px solid lightgrey;
      transition: all 0.3s ease;
    }
    input[type="radio"] {
      display: none;
    }
    #option-1:checked:checked ~ .option-1,
    #option-3:checked:checked ~ .option-3,
    #option-2:checked:checked ~ .option-2 {
      border-color: #0069d9;
      background: #0069d9;
    }
    #option-1:checked:checked ~ .option-1 .dot,
    #option-3:checked:checked ~ .option-3 .dot,
    #option-2:checked:checked ~ .option-2 .dot {
      background: #fff;
    }
    #option-1:checked:checked ~ .option-1 .dot::before,
    #option-3:checked:checked ~ .option-3 .dot::before,
    #option-2:checked:checked ~ .option-2 .dot::before {
      opacity: 1;
      transform: scale(1);
    }
    .option span {
      font-size: 20px;
      color: #808080;
    }
    #option-1:checked:checked ~ .option-1 span,
    #option-3:checked:checked ~ .option-3 span,
    #option-2:checked:checked ~ .option-2 span {
      color: #fff;
    }
  </style>
  <body class="bg-gray-300" style="font-family: Roboto">
    <div class="h-screen flex justify-center items-center">
      <div class="bg-white rounded-lg w-4/5 max-w-2xl px-16 py-16">
        <form action="{% url 'accounts:signup' %}" method="post">
          {% csrf_token %}
          <div class="flex font-bold justify-center">
            <a href="{% url 'homePage' %}">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                version="1.1"
                id="Layer_1"
                x="0px"
                y="0px"
                viewbox="0 0 117 113"
                style="enable-background: new 0 0 117 113"
                xml:space="preserve"
                class="fill-current text-white h-12 w-12 mr-2"
              >
                <style type="text/css">
                  .st0 {
                    fill: #ff9900;
                  }
                </style>
                <g
                  transform="translate(0.000000,113.000000) scale(0.100000,-0.100000)"
                >
                  <path
                    class="st0"
                    d="M145,961v-50h203h203l1,50l1,50H349H145V961z M525,966c0-14-6-25-12-26c-76-3-331,1-338,6c-7,4-6,13,0,26   c10,18,23,19,180,19h170V966z"
                  ></path>
                  <path
                    class="st0"
                    d="M903,761l3-250H770H633l4-47l3-48l183-3l182-2v300v300h-52h-53L903,761z M977,739c2-139,2-263,0-275   c-3-23-5-23-161-23H658l5,25c4,25,5,25,116,25c74,0,118,4,129,13c19,14,24,81,26,335c1,144,2,152,21,152S974,982,977,739z"
                  ></path>
                  <path
                    class="st0"
                    d="M145,599V411h50h49l3,136l3,136l127-1l127-2l-1,50v50l-179,3l-179,3V599z M480,739c-2-22-6-23-93-24   c-50-1-96-5-102-9s-18-1-27,7c-9,7-14,8-10,2c3-6-2-20-12-30c-14-16-17-35-16-109c1-50,0-100-3-112c-6-31-38-30-44,1   c-4,19-3,195,1,279c1,15,15,17,154,17C481,761,482,761,480,739z"
                  ></path>
                </g>
                <path
                  class="st0"
                  d="M7.7,84.6c0,1,10,1.2,50.5,1.1c28.5,0,50.7-0.5,51-1c0.4-0.5-20.7-1-50.5-1.1C17.7,83.4,7.7,83.6,7.7,84.6z"
                ></path>
              </svg>
            </a>
          </div>
          <h2 class="text-3xl text-center text-gray-700 mb-4">Signup Form</h2>
          <div
            class="input-div border-b-2 relative grid my-5 py-1 focus:outline-none"
            style="grid-template-columns: 7% 93%"
          >
            <div class="i">
              <i class="fas fa-user"></i>
            </div>
            <div class="div">
              <h5>Username</h5>
              <input
                type="text"
                class="absolute w-full h-full py-2 px-3 outline-none inset-0 text-gray-700"
                style="background: none"
                name="username"
              />
            </div>
          </div>
          <div
            class="input-div border-b-2 relative grid my-5 py-1 focus:outline-none"
            style="grid-template-columns: 7% 93%"
          >
            <div class="i">
              <i class="fab fa-instagram-square"></i>
            </div>
            <div class="div">
              <h5>Instagram Id</h5>
              <input
                type="text"
                class="absolute w-full h-full py-2 px-3 outline-none inset-0 text-gray-700"
                style="background: none"
                name="Instagram"
              />
            </div>
          </div>
          <div
            class="input-div border-b-2 relative grid my-5 py-1 focus:outline-none"
            style="grid-template-columns: 7% 93%"
          >
            <div class="i">
              <i class="fas fa-lock"></i>
            </div>
            <div class="div">
              <h5>Password</h5>
              <input
                type="password"
                class="absolute w-full h-full py-2 px-3 outline-none inset-0 text-gray-700"
                style="background: none"
                name="password"
              />
            </div>
          </div>
          <div
            class="input-div border-b-2 relative grid my-5 py-1 focus:outline-none"
            style="grid-template-columns: 7% 93%"
          >
            <div class="i">
              <i class="fas fa-check-square"></i>
            </div>
            <div class="div">
              <h5>Confirm</h5>
              <input
                type="password"
                class="absolute w-full h-full py-2 px-3 outline-none inset-0 text-gray-700"
                style="background: none"
                name="Confirm"
              />
            </div>
          </div>
          <div
            class="input-div border-b-2 relative grid my-5 py-1 focus:outline-none"
            style="grid-template-columns: 7% 93%"
          >
            <div class="i">
              <i class="fas fa-envelope"></i>
            </div>
            <div class="div">
              <h5>Email</h5>
              <input
                type="text"
                class="absolute w-full h-full py-2 px-3 outline-none inset-0 text-gray-700"
                style="background: none"
                name="email"
              />
            </div>
          </div>
          <div class="containerra">
            <input type="radio" name="type" id="option-1" value="Influencer" />
            <input type="radio" name="type" id="option-2" value="Manufacture" disabled />
            <input type="radio" name="type" id="option-3" value="Sponsor" />
            <label
              for="option-1"
              class="option option-1"
              style="display: inline"
            >
              <span>Influencer</span>
            </label>
            <label
              for="option-2"
              class="option option-2"
              style="display: inline"
            >
              <span>Manufacture</span>
            </label>
            <label
              for="option-3"
              class="option option-3"
              style="display: inline"
            >
              <span>Sponsor</span>
            </label>
          </div>
          {% if haserror %}
          <p class="font-bold text-red-800 pt-5 ml-3">{{error}}!</p>
          {% endif %}
          <button
            type="submit"
            class="w-full py-2 rounded-full bg-green-600 text-gray-100 focus:outline-none mt-4"
          >
            Signup
          </button>
        </form>
      </div>
    </div>
    <script>
      const inputs = document.querySelectorAll("input");

      function addcl() {
        let parent = this.parentNode.parentNode;
        parent.classList.add("focus");
      }

      function remcl() {
        let parent = this.parentNode.parentNode;
        if (this.value == "") {
          parent.classList.remove("focus");
        }
      }

      inputs.forEach((input) => {
        input.addEventListener("focus", addcl);
        input.addEventListener("blur", remcl);
      });
    </script>
  </body>
</html>

templates/sponsors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/sponsors.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">
    <title>Sponsors page</title>
</head>
<body>
    {% for i in influs %}
    <a href="../{{i.user.username}} ">
    <div class="container">
        <div class="svg-background"></div>
        <div class="svg-background2"></div>
        <img class="profile-img" src="../../static/profs/{{i.Instagram}}.jpg" >
        <div class="text-container">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">id</th>
                    <th scope="col">money needed</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{i.Instagram}}</td>
                    <td>{{i.money}}$</td>
                  </tr>
                </tbody>
              </table>
        </div>
    </div> 
    </a>
    {% endfor %} 
</body>
</html>

templates/verify.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Verify Page</title>
</head>
<body>
    {% if verified %}
        <div>
            <p>Your account verified successfully!</p>
            <p>You can now move to <a href="{% url 'accounts:loginpage' %}">login</a> page</p>
        </div>
    {% else %}
        <div><p>Please verify your instagram account first then try again!</p></div>
    {% endif %}
</body>
</html>